language: d
sudo: false
install:
  - ./travis_install.sh

matrix:
    include:
        - d: dmd
        - d: dmd-2.078.1
        - d: dmd-2.077.1
        - d: dmd-2.076.1
        - d: dmd-2.075.1
        - d: dmd-2.074.1
        - d: ldc
        - d: ldc-1.4.0
        - d: ldc-1.3.0
        - d: ldc-1.2.0

script:
  - dub test
  - dub build
